model_name: lowlight_underwater
output_dir: ../../outputs/D2_seathru/
vis: viewer
visualization_system: colmap
downscale_factor: 1
colmap_path: ../../datasets/D2_seathru/sparse/0
images_path: ../../datasets/D2_seathru/images
pipeline:
  model:
    enhance-enable: True
    water_splatting_loss: True
    bs_loss_enable: False
    gray_loss_enable: False
    white_balance_loss: True
    zero_medium: False
    one_color: True
    cull_alpha_thresh: 0.1
    sh_degree: 3
    wb_clamp: 5
